[tool.poetry]
name = "just-agents"
version = "0.4.6"
description = "Just Agents - A lightweight, straightforward library for LLM agents that focuses on simplicity over unnecessary abstractions."
authors = [
    "Alex Karmazin <karmazinalex@gmail.com>",
    "Newton Winter <isoutthere@gmail.com>",
    "Anton Kulaga <antonkulaga@gmail.com>"
]
maintainers = [
    "Anton Kulaga <antonkulaga@gmail.com>",
    "Newton Winter <isoutthere@gmail.com>"
]
readme = "README.md"
license = "MIT"
keywords = ["python", "llm", "agents", "AI", "machine-learning"]
packages = [{include = "just_agents"}]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
just-agents-core = { path = "core", develop = true }
just-agents-tools = { path = "tools", develop = true }
just-agents-coding = { path = "coding", develop = true }
just-agents-web = { path = "web", develop = true }
just-agents-router = { path = "router", develop = true }
just-agents-examples = { path = "examples", develop = true }

[tool.poetry.group.publish.dependencies]
just-agents-core = "0.4.6"
just-agents-tools = "0.4.6"
just-agents-coding = "0.4.6"
just-agents-web = "0.4.6"
just-agents-router = "0.4.6"
just-agents-examples = "0.4.6"

[tool.poetry.group.dev.dependencies]
pytest = ">=8.3.4"
python-dotenv = "*"

[tool.poetry.scripts]
run-agent = "just_agents.web.run:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"